apiVersion: apps/v1
kind: Deployment
metadata:
  name: tracker
  labels:
    app: tracker
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: tracker
  template:
    metadata:
      labels:
        app: tracker
    spec:
      containers:
        - name: tracker
          image: 192.168.67.133:80/fleetman/position-tracker:latest
          env:
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: tracker-config
                  key: SPRING_PROFILES_ACTIVE
            - name: spring.activemq.broker-url
              valueFrom:
                configMapKeyRef:
                  name: tracker-config
                  key: spring.activemq.broker-url
            - name: fleetman.position.queue
              valueFrom:
                configMapKeyRef:
                  name: tracker-config
                  key: fleetman.position.queue
            - name: spring.data.mongodb.host
              valueFrom:
                configMapKeyRef:
                  name: tracker-config
                  key: spring.data.mongodb.host
            - name: spring.data.mongodb.port
              valueFrom:
                configMapKeyRef:
                  name: tracker-config
                  key: spring.data.mongodb.port
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
      imagePullSecrets:
        - name: harbor-secret

---
apiVersion: v1
kind: Service
metadata:
  name: fleetman-position-tracker
  labels:
    app: tracker
spec:
  selector:
    app: tracker
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: http
  type: ClusterIP

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: tracker-config
data:
  SPRING_PROFILES_ACTIVE: production-microservice
  spring.activemq.broker-url: tcp://fleetman-queue.default.svc.cluster.local:61616
  fleetman.position.queue: positionQueue
  spring.data.mongodb.host: fleetman-mongodb.default.svc.cluster.local
  spring.data.mongodb.port: "27017"
